language: ruby

rvm:
  - 2.5.6
  - 2.6.4

script:
  - bundle exec govuk-lint-ruby lib spec
  - bundle exec rspec -fd

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
