language: ruby

# cache: bundler

rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.1

script:
  - make ruby-lint
  - make rspec
  - make nanoc-check-all

env:
  - RAILS_VERSION=5.2.4
  - RAILS_VERSION=6.0.3

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
